[tool.poetry]
name = "server-assignment"
version = "0.1.0"
description = ""
authors = ["Yelong Hartl-He <Yelong.he@hotmail.com>"]


[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.2"
uvicorn = "^0.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
